### ISSUE TITLE
Metrics for tracking project success

### ISSUE THREAD

**Issue by Phoebecdy91** [zowe/zlc#257]
Monthly tracking:
**Overall** - Holly
- [ ] # of contributor
- [ ] # of committer
-----------------
**Usage:**
- [ ] # of Zowe Chat download - contact Rajpreet
- [ ] # of organization/user using Zowe Chat
- [ ] # of channel new member: **Nov 1 - 38**
-----------------
**Development** - Dev team
- [ ] # of Github issues raised by users
-----------------
**Design:** - UX & CD
- [ ] # of usability test
- [ ] # of webpage view
- [ ] # of survey responses
-----------------
**Go-to-Market** 
(need some place to document all the blog link and engagement activities)
- [ ] # of different channels: social media, conference, websites

Blogs:
- [ ] # of blog
- [ ] # of view of each blog 

Conferents:
- [ ] # of event/conference/sharing session
- [ ] # of attendees
